/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        page: 'hsl(var(--page))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        status: {
          todo: { bg: 'hsl(var(--status-todo-bg))', text: 'hsl(var(--status-todo-text))' },
          progress: { bg: 'hsl(var(--status-in-progress-bg))', text: 'hsl(var(--status-in-progress-text))' },
          done: { bg: 'hsl(var(--status-done-bg))', text: 'hsl(var(--status-done-text))' },
          blocked: { bg: 'hsl(var(--status-blocked-bg))', text: 'hsl(var(--status-blocked-text))' },
        },
        priority: {
          highest: { bg: 'hsl(var(--priority-highest-bg))', text: 'hsl(var(--priority-highest-text))' },
          high: { bg: 'hsl(var(--priority-high-bg))', text: 'hsl(var(--priority-high-text))' },
          medium: { bg: 'hsl(var(--priority-medium-bg))', text: 'hsl(var(--priority-medium-text))' },
          low: { bg: 'hsl(var(--priority-low-bg))', text: 'hsl(var(--priority-low-text))' },
        },
        jira: {
          N0: '#FFFFFF',
          N10: '#FAFBFB',
          N20: '#F4F5F7',
          N30: '#EBECF0',
          N40: '#DFE1E6',
          N50: '#C1C7D0',
          N60: '#B3BAC5',
          N70: '#A5ADBA',
          N80: '#97A0AF',
          N90: '#8993A4',
          N100: '#7A869A',
          N200: '#6B778C',
          N300: '#5E6C84',
          N400: '#505F79',
          N500: '#42526E',
          N600: '#344563',
          N700: '#253858',
          N800: '#172B4D',
          N900: '#091E42',
          B50: '#DEEBFF',
          B75: '#B3D4FF',
          B100: '#4C9AFF',
          B200: '#2684FF',
          B300: '#0065FF',
          B400: '#0052CC',
          B500: '#0747A6',
          G50: '#E3FCEF',
          G200: '#57D9A3',
          G300: '#36B37E',
          G400: '#00875A',
          Y50: '#FFF7CC',
          Y200: '#FFC400',
          Y300: '#FFAB00',
          R50: '#FFEBE6',
          R200: '#FF5630',
          R300: '#DE350B',
          P50: '#EAE6FF',
          P300: '#6554C0',
          T50: '#E6FCFF',
          T300: '#00B8D9',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Atlassian Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Atlassian Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'jira-heading-xxl': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'jira-heading-xl': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'jira-heading-l': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'jira-heading-m': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'jira-heading-s': ['16px', { lineHeight: '24px', fontWeight: '700' }],
        'jira-heading-xs': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'jira-heading-xxs': ['12px', { lineHeight: '16px', fontWeight: '700' }],
        'jira-body-l': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'jira-body-m': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'jira-body-s': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'jira-metric-l': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'jira-metric-m': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'jira-metric-s': ['16px', { lineHeight: '24px', fontWeight: '700' }],
        'jira-code': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'jira-lozenge': ['11.5px', { lineHeight: '1', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm: 'calc(var(--radius) - 1px)',
        md: 'calc(var(--radius) + 1px)',
        lg: 'calc(var(--radius) + 2px)',
      },
      boxShadow: {
        'jira-raised': '0 1px 1px rgba(9, 30, 66, 0.25)',
        'jira-overlay': '0 12px 24px rgba(9, 30, 66, 0.25)',
        'jira-modal': '0 12px 24px -6px rgba(9, 30, 66, 0.25), 0 0 1px rgba(9, 30, 66, 0.31)',
        'jira-card-hover': '0 2px 4px rgba(9, 30, 66, 0.25)',
      },
      transitionDuration: {
        'jira-fast': '150ms',
        'jira-normal': '200ms',
        'jira-slow': '300ms',
      },
      transitionTimingFunction: {
        'jira-ease': 'cubic-bezier(0.15, 1, 0.3, 1)',
      },
      keyframes: {
        'jira-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'jira-slide-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'jira-slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'jira-scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'jira-bounce-in': {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { transform: 'scale(1.1)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'jira-sidebar-collapse': {
          '0%': { width: '240px' },
          '100%': { width: '64px' },
        },
        'jira-sidebar-expand': {
          '0%': { width: '64px' },
          '100%': { width: '240px' },
        },
        'jira-pulse-skeleton': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '1' },
        },
      },
      animation: {
        'jira-fade-in': 'jira-fade-in 200ms ease-out',
        'jira-slide-up': 'jira-slide-up 200ms ease-out',
        'jira-slide-down': 'jira-slide-down 200ms ease-out',
        'jira-scale-in': 'jira-scale-in 200ms ease-out',
        'jira-bounce-in': 'jira-bounce-in 400ms ease-out',
        'jira-sidebar': 'jira-sidebar-collapse 300ms ease-in-out',
        'jira-pulse': 'jira-pulse-skeleton 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
